# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

services:
  animation-compositor:
    restart: unless-stopped
    container_name: animation-compositor
    image: animation-compositor:latest
    depends_on:
      robot-controller:
        condition: service_healthy
      redpanda:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: ./pyproject.toml
        - action: sync+restart
          path: ./src
          target: /app/src
    build:
      context: ..
      dockerfile: animation-compositor-service/Dockerfile
    environment:
      - XDG_RUNTIME_DIR=/run/user/1000
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
    devices:
      - /dev/snd:/dev/snd # Audio devices
    volumes:
      - /run/user/1000/pulse:/run/user/1000/pulse
      - /run/user/1000/pulse/native:/run/user/1000/pulse/native
      - /run/user/1000/pipewire-0:/run/user/1000/pipewire-0
      - /run/user/1000/pipewire-0.lock:/run/user/1000/pipewire-0.lock
      - /run/user/1000/pipewire-0-manager:/run/user/1000/pipewire-0-manager
      - /run/user/1000/pipewire-0-manager.lock:/run/user/1000/pipewire-0-manager.lock
    #configs:
    #  - source: config_animation_compositor
    #    target: /config.yaml

#configs:
#  config_animation_compositor:
#    content: |
#      audio_config:
#        output_devices_index_or_name: ["Reachy Mini Audio"]
#        sample_rate: 16000
